name: Deploy
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          ref: main
          submodules: recursive

      - name: Checkout destination
        uses: actions/checkout@v5
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.148.2/hugo_extended_0.148.2_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo
          chmod +x ${RUNNER_TEMP}/hugo

      - name: Build
        run: ${RUNNER_TEMP}/hugo build --minify --baseURL 'https://madin-prime.github.io'

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config user.name 'Nafiu Hasan Madin'
          git config user.email 'nafiuhasanmadin@gmail.com'
          git commit -m 'Deploy to GitHub Pages'
          git push